### PR TITLE
Bump version of Clustering.jl

### PR DESCRIPTION
**Pull request by juliohm**
@ablaom can you please review and merge? This is holding some downstream updates.

### CODE REVIEW

**Comment by juliohm** [comment]
I followed the [release notes](https://github.com/JuliaStats/Clustering.jl/releases/tag/v0.15.0) of Clustering.jl, but the tests are still failing here.

**Comment by ablaom** [comment]
@alyst Is it possible some undocumented change in DBSCAN for Clustering.jl  has broken this package (MLJClusteringInterface.jl) - see tests above? It looks like labels are getting mixed up. Any idea what the issue might be?

**Comment by alyst** [comment]
@ablaom There was some breaking API change in 0.15 along with some bugfixes in the algorithm implementation (see JuliaStats/Clustering.jl/pull/248 for both).
I don't think the test of *MLJClusteringInterface.jl* is failing because of the API incompatibility.
However, there was a bug that resulted in the DBSCAN cluster without the "core" being created.
From what I can see in your test logs, the test fails because now the points are annotated as "core", not "boundaries" (`['C', 'C', 'C', 'C', 'C']`).
I guess it is the correct output, but you can double-check. And maybe you can add a test, where the clusters have both the core and the boundary.

**Comment by ablaom** [comment]
@alyst Thanks for your prompt and considered reply. I'll take a closer look.

**Comment by ablaom** [comment]
closed in favour of #25

**Pull request closed without merging**
